services:
  # === MONITORING ===
  mon-loki:
    image: grafana/loki:3.0.0
    container_name: ${LOKI_CONTAINER_NAME:-mon-loki}
    ports:
      - "${LOKI_PORT:-3100}:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki

  mon-tempo:
    image: grafana/tempo:2.4.1
    container_name: ${TEMPO_CONTAINER_NAME:-mon-tempo}
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
      - tempo_data:/tmp/tempo
    ports:
      - "${TEMPO_PORT:-3200}:3200"

  mon-prometheus:
    image: prom/prometheus:v2.53.0
    container_name: ${PROMETHEUS_CONTAINER_NAME:-mon-prometheus}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  mon-otel:
    image: otel/opentelemetry-collector-contrib:0.106.1
    container_name: ${OTEL_COLLECTOR_CONTAINER_NAME:-mon-otel}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "${OTEL_COLLECTOR_GRPC_PORT:-4317}:4317"
      - "${OTEL_COLLECTOR_HTTP_PORT:-4318}:4318"
    depends_on:
      - mon-loki
      - mon-tempo

  mon-grafana:
    image: grafana/grafana:11.0.0
    container_name: ${GRAFANA_CONTAINER_NAME:-mon-grafana}
    depends_on:
      - mon-loki
      - mon-tempo
      - mon-prometheus
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  loki_data:
  tempo_data:
  prometheus_data:
  grafana_data:
