global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: auth
    metrics_path: /metrics
    static_configs:
      - targets: ["auth:8080"]
        labels:
          service: auth

  - job_name: gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8080"]
        labels:
          service: gateway
