global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: srv-auth
    metrics_path: /metrics
    static_configs:
      - targets: ["srv-auth:8080"]
        labels:
          service: srv-auth

  - job_name: srv-organization
    metrics_path: /metrics
    static_configs:
      - targets: ["srv-organization:8080"]
        labels:
          service: srv-organization

  - job_name: srv-notification
    metrics_path: /metrics
    static_configs:
      - targets: ["srv-notification:8080"]
        labels:
          service: srv-notification

  - job_name: srv-bff
    metrics_path: /metrics
    static_configs:
      - targets: ["srv-bff:8080"]
        labels:
          service: srv-bff

  - job_name: gw-api
    metrics_path: /metrics
    static_configs:
      - targets: ["gw-api:8080"]
        labels:
          service: gw-api

  - job_name: gw-nginx
    static_configs:
      - targets: ["mon-nginx-exporter:9113"]
        labels:
          service: gw-nginx
